### ISSUE TITLE
Problem 2... Alarm Repeat

### ISSUE THREAD

**Issue by RoboCop0815** [Shaztech/Pilldispenser#10]
... there is no repetition of the alarm message after 5 minutes.

**Comment by Shaztech** [comment]
Alarm message of telegram ?

**Comment by Shaztech** [comment]
![image](https://github.com/Shaztech/Pilldispenser/assets/16314016/d85a920e-b01a-4843-a5dc-0b57c2a6d782)
This only means that if you enter 19:13 on the web page, it will be converted to 19:15.
It doesn't mean that it will alert you at 5 min intervals... The sound alert is at 1 min interval and cannot be changed by the user.

**Comment by RoboCop0815** [comment]
OK, then I misunderstood it and it seems to work... :-)
