### ISSUE TITLE
24 hours clock question + generic pill taking question

### ISSUE THREAD

**Issue by gitterman** [Shaztech/Pilldispenser#13]
I am in the process of building your ingenious project and found that the web interface shows a 12-hour clock, whereas the LCD shows a 24-hour clock.
My PCs and my phone are US English because of business use, but I'd like to have an unambiguous 24-hour clock on the web interface too. Is that possible?
For the general understanding: 
  If I have to take pills A in the morning, pills B at noon, pills C in the afternoon and pills D at bedtime, how do I set need to set this up?
  Do I need 4 separate trays just for me then?
  Or is it possible to put 4 alarms on the same tray in 4 different slots?

**Comment by Shaztech** [comment]
![image](https://github.com/user-attachments/assets/53d80cd3-4575-497a-95da-ceee65ef6d8b)
The web interface is already in 24h format. Maybe it's OS dependent (Windows clock settings)
Yes 4 trays, because the goal of this device was to refill it only once per month (30 days).
It will be a pain to refill certains tray after 7 days others 10 days, etc.

**Comment by gitterman** [comment]
Thanks for the quick answer.
I did run the web interface on my android phone.
For the tray issue, I understand now.
It is a pity, though, if you need to take pills only for a certain amount of time (less than a month).
E. g. I got prescription of cortisone for 14 days and I need to take a pill for stomach protection an hour before I take the cortisone pills.
Nonetheless, I understand your point of view and if I have time I will check if I can tailor the code for my needs.
BTW: there is a slight typo on the LCD screen. When you adjust the slot, the message says "adjustement" instead of adjustment.
