### ISSUE TITLE
Is there any way to convert the project to raspberry pi

### ISSUE THREAD

**Issue by bob5731** [Shaztech/Pilldispenser#17]
I was thinking about using a raspberry pi 3B+ to run the project. I tried compiling it on a MacBook Air early 2011 running 10.15.7 but it refuses to compile due to incompatibility issues with the offering system being too old. I don't currently have my Arduino boards where I'm at so I'd like to see if there's a way that I can use an emulator or something else to run the project and see if it will meet my needs before printing all of the parts. Would also help if you could drop all the parts into single STL files and then zip them up.

**Comment by Shaztech** [comment]
Too much job and I don't know linux that much... It's made for an ESP32 with a touch screen. It's not a "software" it's directly hardcoded for the hardware. Also if you want the stl, go to makerworld (with the link) to download them.
