### ISSUE TITLE
LCD Screen - Purchased part

### ISSUE THREAD

**Issue by tavenhall1** [Shaztech/Pilldispenser#2]
Hello, I haven't been able to find any mention of what the requirement are for the LCD screen (ie size/type/connection/etc). It's possible I missed it, so feel free to point me to that information. Can you also add it to the list of purchased parts?

Thanks!

**Comment by Shaztech** [comment]
The lcd is with the ESP32 module:
P1 - ESP-32 WROOM Development Board (Called CYD "Cheap Yellow Display") [1x]
[https://www.aliexpress.com/item/1005006604267846.html](url)
[https://www.amazon.ca/DIYmalls-ESP32-2432S028R-Resistive-ESP-WROOM-32-Development/dp/B0CG2WQGP9](url)
