### ISSUE TITLE
Floating parts in A17 - Top Dust Cap [1x].stl

### ISSUE THREAD

**Issue by ponymorphism** [Shaztech/Pilldispenser#4]
Hello,

first off thanks so much for your tremendous project. Very inspiring!

When printing A17 - Top Dust Cap, I noticed that the two D-shaped parts in the middle of the part seem to be floating about 0.5mm above the main surface. My slicer (OrcaSlicer) even suggested to add supports there (see screenshots).

![Screenshot 2024-03-29 074620](https://github.com/Shaztech/Pilldispenser/assets/3270981/09b2ca42-6819-4450-a627-51a40b788c38)
![Screenshot 2024-03-29 074718](https://github.com/Shaztech/Pilldispenser/assets/3270981/74794423-692a-4c8f-bac1-dda901c0e6ec)

I still tried to print it as it is (without supports), but the D-shapes didn't connect to the surface as expected. My quick fix was now to insert a flattened cube to just fill the gap.

**Comment by Shaztech** [comment]
I fixed it, when I printed mine, the overall part was lower by 1 mm, and wasn't sitting correctly on my trays, so I decided to add 1mm but never tested it. Thanks you !
