### ISSUE TITLE
Problem 1... telegram message

### ISSUE THREAD

**Issue by RoboCop0815** [Shaztech/Pilldispenser#9]
... even though the Telegram test message is received, the messages about taking the pills no longer come, it was already working...
Telegram Alert after: "Instant"

**Comment by Shaztech** [comment]
Is it working if you choose 15 min ?
Mine is set like that and works everytime.
(Instant = +/-30 sec)

**Comment by RoboCop0815** [comment]
OK, I'll set it up and test it.
